"""feat: table Image

Revision ID: 01a1748710fa
Revises: 964fbc16a773
Create Date: 2024-04-02 12:08:01.703373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a1748710fa'
down_revision: Union[str, None] = '964fbc16a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('chair_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chair_id'], ['Chair.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Image')
    # ### end Alembic commands ###
