"""feat: table ChairColor

Revision ID: 41df15d86f47
Revises: 1cef3500d1e3
Create Date: 2024-04-02 12:10:37.804091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41df15d86f47'
down_revision: Union[str, None] = '1cef3500d1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChairColor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('upholstery', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chair_id'], ['Chair.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['Color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChairColor')
    # ### end Alembic commands ###
