"""feat: table Image

Revision ID: 947a0786ab7e
Revises: a9f13791f22a
Create Date: 2024-04-01 16:56:40.220876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947a0786ab7e'
down_revision: Union[str, None] = 'a9f13791f22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('chair_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chair_id'], ['Chair.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Image')
    # ### end Alembic commands ###
